# Generated by Django 3.1 on 2020-09-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200916_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
