# Generated by Django 3.1 on 2020-10-15 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_recipe_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='menu.category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='menu.food'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followed_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
