# Generated by Django 3.1 on 2020-10-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20201015_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
